<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('racks', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('id_ticket')->nullable();
            $table->foreign('id_ticket')
                ->references('id')->on('ticket')
                ->inDelete('set null');

            $table->boolean('r1')->nullable();
            $table->boolean('r2')->nullable();
            $table->boolean('r3')->nullable();
            $table->boolean('r4')->nullable();
            $table->boolean('r5')->nullable();
            $table->boolean('r6')->nullable();
            $table->boolean('r7')->nullable();
            $table->boolean('r8')->nullable();
            $table->boolean('r9')->nullable();
            $table->boolean('r10')->nullable();
            $table->boolean('r11')->nullable();
            $table->boolean('r12')->nullable();
            $table->boolean('r13')->nullable();
            $table->boolean('r14')->nullable();
            $table->boolean('r15')->nullable();
            $table->boolean('r16')->nullable();
            $table->boolean('r17')->nullable();
            $table->boolean('r18')->nullable();
            $table->boolean('r19')->nullable();
            $table->boolean('r20')->nullable();
            $table->boolean('r21')->nullable();
            $table->boolean('r22')->nullable();
            $table->boolean('r23')->nullable();
            $table->boolean('r25')->nullable();
            $table->boolean('r26')->nullable();
            $table->boolean('r27')->nullable();
            $table->boolean('r28')->nullable();
            $table->boolean('r29')->nullable();
            $table->boolean('r30')->nullable();
            $table->boolean('r31')->nullable();
            $table->boolean('r32')->nullable();
            $table->boolean('r33')->nullable();
            $table->boolean('r34')->nullable();
            $table->boolean('r35')->nullable();
            $table->boolean('r36')->nullable();
            $table->boolean('r37')->nullable();
            $table->boolean('r38')->nullable();
            $table->boolean('r39')->nullable();
            $table->boolean('r40')->nullable();
            $table->boolean('r41')->nullable();
            $table->boolean('r42')->nullable();
            $table->boolean('r43')->nullable();
            $table->boolean('r44')->nullable();
            $table->boolean('r45')->nullable();
            $table->boolean('r46')->nullable();
            $table->boolean('r47')->nullable();
            $table->boolean('r48')->nullable();
            $table->boolean('r49')->nullable();
            $table->boolean('r50')->nullable();
            $table->boolean('r51')->nullable();
            $table->boolean('r52')->nullable();
            $table->boolean('r53')->nullable();
            $table->boolean('r54')->nullable();
            $table->boolean('r55')->nullable();
            $table->boolean('r56')->nullable();
            $table->boolean('r57')->nullable();
            $table->boolean('r58')->nullable();
            $table->boolean('r59')->nullable();
            $table->boolean('r60')->nullable();
            $table->boolean('r61')->nullable();
            $table->boolean('r62')->nullable();
            $table->boolean('r63')->nullable();
            $table->boolean('r64')->nullable();
            $table->boolean('r65')->nullable();
            $table->boolean('r66')->nullable();
            $table->boolean('r67')->nullable();
            $table->boolean('r68')->nullable();
            $table->boolean('r69')->nullable();
            $table->boolean('r70')->nullable();
            $table->boolean('r71')->nullable();
            $table->boolean('r72')->nullable();
            $table->boolean('r73')->nullable();
            $table->boolean('r74')->nullable();
            $table->boolean('r75')->nullable();
            $table->boolean('r76')->nullable();
            $table->boolean('r77')->nullable();
            $table->boolean('r78')->nullable();
            $table->boolean('r79')->nullable();
            $table->boolean('r80')->nullable();
            $table->boolean('r81')->nullable();
            $table->boolean('r82')->nullable();
            $table->boolean('r83')->nullable();
            $table->boolean('r84')->nullable();
            $table->boolean('r85')->nullable();
            $table->boolean('r86')->nullable();
            $table->boolean('r87')->nullable();
            $table->boolean('r88')->nullable();
            $table->boolean('r89')->nullable();
            $table->boolean('r90')->nullable();
            $table->boolean('r91')->nullable();
            $table->boolean('r92')->nullable();
            $table->boolean('r93')->nullable();
            $table->boolean('r94')->nullable();
            $table->boolean('r95')->nullable();
            $table->boolean('r96')->nullable();
            $table->boolean('r97')->nullable();
            $table->boolean('r98')->nullable();
            $table->boolean('r99')->nullable();
            $table->boolean('r101')->nullable();
            $table->boolean('r102')->nullable();
            $table->boolean('r103')->nullable();
            $table->boolean('r104')->nullable();
            $table->boolean('r105')->nullable();
            $table->boolean('r106')->nullable();
            $table->boolean('r107')->nullable();
            $table->boolean('r108')->nullable();
            $table->boolean('r109')->nullable();
            $table->boolean('r110')->nullable();
            $table->boolean('r111')->nullable();
            $table->boolean('r112')->nullable();
            $table->boolean('r113')->nullable();
            $table->boolean('r114')->nullable();
            $table->boolean('r115')->nullable();
            $table->boolean('r116')->nullable();
            $table->boolean('r117')->nullable();
            $table->boolean('r118')->nullable();
            $table->boolean('r119')->nullable();
            $table->boolean('r120')->nullable();
            $table->boolean('r121')->nullable();
            $table->boolean('r122')->nullable();
            $table->boolean('r123')->nullable();
            $table->boolean('r125')->nullable();
            $table->boolean('r126')->nullable();
            $table->boolean('r127')->nullable();
            $table->boolean('r128')->nullable();
            $table->boolean('r129')->nullable();
            $table->boolean('r130')->nullable();
            $table->boolean('r131')->nullable();
            $table->boolean('r132')->nullable();
            $table->boolean('r133')->nullable();
            $table->boolean('r134')->nullable();
            $table->boolean('r135')->nullable();
            $table->boolean('r136')->nullable();
            $table->boolean('r137')->nullable();
            $table->boolean('r138')->nullable();
            $table->boolean('r139')->nullable();
            $table->boolean('r140')->nullable();
            $table->boolean('r141')->nullable();
            $table->boolean('r142')->nullable();
            $table->boolean('r143')->nullable();
            $table->boolean('r144')->nullable();
            $table->boolean('r145')->nullable();
            $table->boolean('r146')->nullable();
            $table->boolean('r147')->nullable();
            $table->boolean('r148')->nullable();
            $table->boolean('r149')->nullable();
            $table->boolean('r150')->nullable();
            $table->boolean('r151')->nullable();
            $table->boolean('r152')->nullable();
            $table->boolean('r153')->nullable();
            $table->boolean('r154')->nullable();
            $table->boolean('r155')->nullable();
            $table->boolean('r156')->nullable();
            $table->boolean('r157')->nullable();
            $table->boolean('r158')->nullable();
            $table->boolean('r159')->nullable();
            $table->boolean('r160')->nullable();
            $table->boolean('r161')->nullable();
            $table->boolean('r162')->nullable();
            $table->boolean('r163')->nullable();
            $table->boolean('r164')->nullable();
            $table->boolean('r165')->nullable();
            $table->boolean('r166')->nullable();
            $table->boolean('r167')->nullable();
            $table->boolean('r168')->nullable();
            $table->boolean('r169')->nullable();
            $table->boolean('r170')->nullable();
            $table->boolean('r171')->nullable();
            $table->boolean('r172')->nullable();
            $table->boolean('r173')->nullable();
            $table->boolean('r174')->nullable();
            $table->boolean('r175')->nullable();
            $table->boolean('r176')->nullable();
            $table->boolean('r177')->nullable();
            $table->boolean('r178')->nullable();
            $table->boolean('r179')->nullable();
            $table->boolean('r180')->nullable();
            $table->boolean('r181')->nullable();
            $table->boolean('r182')->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('racks');
    }
};
