<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('racks', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('id_ticket')->nullable();
            $table->foreign('id_ticket')
                ->references('id')->on('ticket')
                ->inDelete('set null');

            $table->boolean('1')->nullable();
            $table->boolean('2')->nullable();
            $table->boolean('3')->nullable();
            $table->boolean('4')->nullable();
            $table->boolean('5')->nullable();
            $table->boolean('6')->nullable();
            $table->boolean('7')->nullable();
            $table->boolean('8')->nullable();
            $table->boolean('9')->nullable();
            $table->boolean('10')->nullable();
            $table->boolean('11')->nullable();
            $table->boolean('12')->nullable();
            $table->boolean('13')->nullable();
            $table->boolean('14')->nullable();
            $table->boolean('15')->nullable();
            $table->boolean('16')->nullable();
            $table->boolean('17')->nullable();
            $table->boolean('18')->nullable();
            $table->boolean('19')->nullable();
            $table->boolean('20')->nullable();
            $table->boolean('21')->nullable();
            $table->boolean('22')->nullable();
            $table->boolean('23')->nullable();
            $table->boolean('25')->nullable();
            $table->boolean('26')->nullable();
            $table->boolean('27')->nullable();
            $table->boolean('28')->nullable();
            $table->boolean('29')->nullable();
            $table->boolean('30')->nullable();
            $table->boolean('31')->nullable();
            $table->boolean('32')->nullable();
            $table->boolean('33')->nullable();
            $table->boolean('34')->nullable();
            $table->boolean('35')->nullable();
            $table->boolean('36')->nullable();
            $table->boolean('37')->nullable();
            $table->boolean('38')->nullable();
            $table->boolean('39')->nullable();
            $table->boolean('40')->nullable();
            $table->boolean('41')->nullable();
            $table->boolean('42')->nullable();
            $table->boolean('43')->nullable();
            $table->boolean('44')->nullable();
            $table->boolean('45')->nullable();
            $table->boolean('46')->nullable();
            $table->boolean('47')->nullable();
            $table->boolean('48')->nullable();
            $table->boolean('49')->nullable();
            $table->boolean('50')->nullable();
            $table->boolean('51')->nullable();
            $table->boolean('52')->nullable();
            $table->boolean('53')->nullable();
            $table->boolean('54')->nullable();
            $table->boolean('55')->nullable();
            $table->boolean('56')->nullable();
            $table->boolean('57')->nullable();
            $table->boolean('58')->nullable();
            $table->boolean('59')->nullable();
            $table->boolean('60')->nullable();
            $table->boolean('61')->nullable();
            $table->boolean('62')->nullable();
            $table->boolean('63')->nullable();
            $table->boolean('64')->nullable();
            $table->boolean('65')->nullable();
            $table->boolean('66')->nullable();
            $table->boolean('67')->nullable();
            $table->boolean('68')->nullable();
            $table->boolean('69')->nullable();
            $table->boolean('70')->nullable();
            $table->boolean('71')->nullable();
            $table->boolean('72')->nullable();
            $table->boolean('73')->nullable();
            $table->boolean('74')->nullable();
            $table->boolean('75')->nullable();
            $table->boolean('76')->nullable();
            $table->boolean('77')->nullable();
            $table->boolean('78')->nullable();
            $table->boolean('79')->nullable();
            $table->boolean('80')->nullable();
            $table->boolean('81')->nullable();
            $table->boolean('82')->nullable();
            $table->boolean('83')->nullable();
            $table->boolean('84')->nullable();
            $table->boolean('85')->nullable();
            $table->boolean('86')->nullable();
            $table->boolean('87')->nullable();
            $table->boolean('88')->nullable();
            $table->boolean('89')->nullable();
            $table->boolean('90')->nullable();
            $table->boolean('91')->nullable();
            $table->boolean('92')->nullable();
            $table->boolean('93')->nullable();
            $table->boolean('94')->nullable();
            $table->boolean('95')->nullable();
            $table->boolean('96')->nullable();
            $table->boolean('97')->nullable();
            $table->boolean('98')->nullable();
            $table->boolean('99')->nullable();
            $table->boolean('101')->nullable();
            $table->boolean('102')->nullable();
            $table->boolean('103')->nullable();
            $table->boolean('104')->nullable();
            $table->boolean('105')->nullable();
            $table->boolean('106')->nullable();
            $table->boolean('107')->nullable();
            $table->boolean('108')->nullable();
            $table->boolean('109')->nullable();
            $table->boolean('110')->nullable();
            $table->boolean('111')->nullable();
            $table->boolean('112')->nullable();
            $table->boolean('113')->nullable();
            $table->boolean('114')->nullable();
            $table->boolean('115')->nullable();
            $table->boolean('116')->nullable();
            $table->boolean('117')->nullable();
            $table->boolean('118')->nullable();
            $table->boolean('119')->nullable();
            $table->boolean('120')->nullable();
            $table->boolean('121')->nullable();
            $table->boolean('122')->nullable();
            $table->boolean('123')->nullable();
            $table->boolean('125')->nullable();
            $table->boolean('126')->nullable();
            $table->boolean('127')->nullable();
            $table->boolean('128')->nullable();
            $table->boolean('129')->nullable();
            $table->boolean('130')->nullable();
            $table->boolean('131')->nullable();
            $table->boolean('132')->nullable();
            $table->boolean('133')->nullable();
            $table->boolean('134')->nullable();
            $table->boolean('135')->nullable();
            $table->boolean('136')->nullable();
            $table->boolean('137')->nullable();
            $table->boolean('138')->nullable();
            $table->boolean('139')->nullable();
            $table->boolean('140')->nullable();
            $table->boolean('141')->nullable();
            $table->boolean('142')->nullable();
            $table->boolean('143')->nullable();
            $table->boolean('144')->nullable();
            $table->boolean('145')->nullable();
            $table->boolean('146')->nullable();
            $table->boolean('147')->nullable();
            $table->boolean('148')->nullable();
            $table->boolean('149')->nullable();
            $table->boolean('150')->nullable();
            $table->boolean('151')->nullable();
            $table->boolean('152')->nullable();
            $table->boolean('153')->nullable();
            $table->boolean('154')->nullable();
            $table->boolean('155')->nullable();
            $table->boolean('156')->nullable();
            $table->boolean('157')->nullable();
            $table->boolean('158')->nullable();
            $table->boolean('159')->nullable();
            $table->boolean('160')->nullable();
            $table->boolean('161')->nullable();
            $table->boolean('162')->nullable();
            $table->boolean('163')->nullable();
            $table->boolean('164')->nullable();
            $table->boolean('165')->nullable();
            $table->boolean('166')->nullable();
            $table->boolean('167')->nullable();
            $table->boolean('168')->nullable();
            $table->boolean('169')->nullable();
            $table->boolean('170')->nullable();
            $table->boolean('171')->nullable();
            $table->boolean('172')->nullable();
            $table->boolean('173')->nullable();
            $table->boolean('174')->nullable();
            $table->boolean('175')->nullable();
            $table->boolean('176')->nullable();
            $table->boolean('177')->nullable();
            $table->boolean('178')->nullable();
            $table->boolean('179')->nullable();
            $table->boolean('180')->nullable();
            $table->boolean('181')->nullable();
            $table->boolean('182')->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('racks');
    }
};
